services:
  cbgl:
    build:
      context: ..
      dockerfile: docker/Dockerfile

    image: li9i/cbgl:latest
    container_name: cbgl_container

    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host
    user: cbgl
    volumes:
      - ../cbgl:/home/cbgl/catkin_ws/src/cbgl/
